### ISSUE TITLE
Crashes Node-Red when Cloudflare session is expired

### ISSUE THREAD

**Issue by dvbportal** [fullmetal-fred/node-red-dashboard-2-cloudflare-auth#5]
When running over days, I get the following exception:

> 8 Jul 07:09:02 - [red] Uncaught Exception:
8 Jul 07:09:02 - [error] TypeError: Cannot set properties of undefined (setting 'user')
at Object.onAddConnectionCredentials (/data/node_modules/@fullmetal-fred/node-red-dashboard-2-cloudflare-auth/src/index.js:33:26)
at /data/node_modules/@flowfuse/node-red-dashboard/nodes/utils/index.js:43:36
at Array.forEach (<anonymous>)
at addConnectionCredentials (/data/node_modules/@flowfuse/node-red-dashboard/nodes/utils/index.js:41:55)
at onAction (/data/node_modules/@flowfuse/node-red-dashboard/nodes/config/ui_base.js:505:19)
at Socket.emit (node:events:517:28)
at Socket.emit (node:domain:489:12)
at Socket.emitUntyped (/data/node_modules/socket.io/dist/typed-events.js:69:22)
at /data/node_modules/socket.io/dist/socket.js:704:39
at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

**Comment by fullmetal-fred** [comment]
Thanks @dvbportal: I think I've figured this out. Look for version 0.1.6 to fix shortly. I've merged a few other changes into this as well...mostly removing the _headers object and adding a few more useful things to the user object.
